### ISSUE TITLE
auth is not lifetime

### ISSUE THREAD

**Issue by Reykira007** [ilyhalight/notpx#2]
![image](https://github.com/user-attachments/assets/da340527-9fde-4b29-88b3-980f35b10249)

**Comment by ilyhalight** [comment]
You need set auth string without `InitData `, only `user=...`, after exiting beta, auth lifetime is 30 minutes

**Comment by ryandhikacc** [comment]
> You need set auth string without `InitData `, only `user=...`, after exiting beta, auth lifetime is 30 minutes

Is there any workaround to automatically renew auth everytime it died?

**Comment by Reykira007** [comment]
perhaps using the token refresh method!

**Comment by ilyhalight** [comment]
> perhaps using the token refresh method!

not pixel doesn't have such a method, you need to restart the webapp to get a new token. perhaps this can be automated using a user bot

**Comment by RedWilly** [comment]
We can use telegram API id and API hash... 

Also I also think we need to work on the user agent too.

**Comment by Reykira007** [comment]
currently telegram is very sensitive. using API id and API hash will make telegram account blocked

**Comment by RedWilly** [comment]
> currently telegram is very sensitive. using API id and API hash will make telegram account blocked

Not if you used that right. Beside running this kinda of bot shouldn't be using your main telegram account - need to use a second account ( that been said you shouldn't login /open the TG app when the bot is running - this is mainly to avoid banned's)

**Comment by ilyhalight** [comment]
Bot migrated to telegram sessions, this issue is no longer relevant
