### ISSUE TITLE
Correct Format for Proxy with Authentication?

### ISSUE THREAD

**Issue by ryandhikacc** [ilyhalight/notpx#3]
Title says it, what is the correct format for proxy with username&password? im using http://ip:port@user:pass and http://ip:port:user:pass but it shows error `Failed to get base config, reason: fetch() proxy URL is invalid`

**Comment by ilyhalight** [comment]
```http://user:pass@ip:port```

detail: https://bun.sh/guides/http/proxy

**Comment by ryandhikacc** [comment]
Its working now, but with the newest update even using template it still getting 0 points

**Comment by ilyhalight** [comment]
Now notpixel is lagging a lot and maybe this is related, but everything works for me personally. Anyway, can you give me a link to the template? I'll check if it's parsing correctly

![Telegram_ZAIVXNegRp](https://github.com/user-attachments/assets/cec05ab8-6cc4-49d1-bcc6-71a9a08bc856)

**Comment by ryandhikacc** [comment]
[https://static.notpx.app/templates/516943213.png](url)

its basically all black template to get max points easier

**Comment by ilyhalight** [comment]
I checked that the template reads correctly. Most likely, this is due to lags
